### ISSUE TITLE
Show size in bytes of CIL method's code in CodeLens

### ISSUE THREAD

**Issue by vvdev** [bert2/microscope#3]
Hello.

It would be great if you could display size of the CIL code of the method in bytes.
It can be shown next to instructions count (like "10 instructions, 20 bytes") or in the pop-up hint.
Also it would be nice to show it in the header of Instructions Details window (like "CodeLens Instructions - Method Name - 10 instructions, 20 bytes")

This information is needed to understand if the method has chance to be inlined by JIT.

Thank you.

**Comment by bert2** [comment]
Hi @vvdev, thanks for the feedback! I'll look into that.

**Comment by bert2** [comment]
Hey @vvdev, I just released a new version (2.2.0) where the method's byte size is shown in the tool tip.

![image](https://user-images.githubusercontent.com/1454629/145498610-0de6e19f-547b-47fe-9ebf-3f2049807c32.png)

Unfortunately it's not possible to change the title of a popped-out code lense window. That title is controlled by Visual Studio's code lense engine.

I considered adding it to the code lense text button itself, but I felt it would waste screen estate. But I'm unsure how often one would check that value and whether a tooltip will slow down the user experience too much. What's your opinion on this?

**Comment by vvdev** [comment]
Hi @bert2 .

Wow :) Great :)

I think it is totally fine to show Size in popup hint. At the moment i would agree that this is the best balance of information available and visual noise. If i get better ideas how to show it i will share with you.

Thank you very much.

**Comment by bert2** [comment]
Perfect :) I'll go ahead and close the ticket for now, but feel free to reopen it when you encounter problems or have new ideas regarding the method byte size display.
